# Task 1
Task 1.1: Write a function called fizzbuzz that takes a number n and returns:\
• "FizzBuzz" if n is divisible by both 3 and 5\
• "Fizz" if n is divisible by 3 only\
• "Buzz" if n is divisible by 5 only\
• The number itself as a string otherwise

In [1]:
def fizzbuzz(n):
    if n % 3 == 0 and n % 5 == 0:
        return "FizzBuzz"
    elif n % 3 == 0:
        return "Fizz"
    elif n % 5 == 0:
        return "Buzz"
    else:
        return str(n)


print(fizzbuzz(15))

FizzBuzz


Task 1.2: Given the following list of dictionaries representing students, write code to:
1. Find the student with the highest grade
2. Calculate the average grade
3. Create a list of names of students who passed (grade >= 60)

In [2]:
students = [
    {"name": "Alice", "grade": 85},
    {"name": "Bob", "grade": 72},
    {"name": "Charlie", "grade": 55},
    {"name": "David", "grade": 91},
    {"name": "Eve", "grade": 68},
]

def highest_grade(students):
    highest_grade = 0

    for student in students:
        if student["grade"] > highest_grade:
            highest_grade = student["grade"]

    return highest_grade

def average_grade(students):
    total_grade = 0
    num_students = len(students)

    for student in students:
        total_grade += student["grade"]
    
    return total_grade/num_students

def passed_students(students):
    pass_list = []

    for student in students:
        if student["grade"] >= 60:
            pass_list.append(student["name"])
    
    return pass_list

print(highest_grade(students))
print(average_grade(students))
print(passed_students(students))

91
74.2
['Alice', 'Bob', 'David', 'Eve']


# Task 2
Task 2.1: Create a 5x5 matrix with values from 1 to 25. Then:
1. Extract the diagonal elements
2. Calculate the sum of each row
3. Find all elements greater than 12
4. Replace all even numbers with 0

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

#Create a 5x5 matrix with zero values
mat_5x5 = np.zeros((5,5))
num = 1

#Load the matrix with value from 1-25
for i in range(mat_5x5.shape[0]):
    for j in range(mat_5x5.shape[1]):
        mat_5x5[i][j] = num
        num+=1

#Extracting the diagonal elements
diag_elements = []
for i in range(mat_5x5.shape[0]):
    for j in range(mat_5x5.shape[1]):
        if i == j:
            diag_elements.append(int(mat_5x5[i][j]))
print(f"The diagonal elements are :{diag_elements}")

#Calculate sum of each row
sum_row = []
for i in range(mat_5x5.shape[0]):
    sum = 0
    for j in range(mat_5x5.shape[1]):
        sum += mat_5x5[i][j]
    sum_row.append(int(sum))
print(f"The sum of each of the rows of the matrix is: {sum_row}")

#Elements greater than 12
elem_12 = []
for i in range(mat_5x5.shape[0]):
    for j in range(mat_5x5.shape[1]):
        if mat_5x5[i][j] > 12:
            elem_12.append(int(mat_5x5[i][j]))
print(f"The elements greater than 12 are :{elem_12}")

#Replace all even number by 0
for i in range(mat_5x5.shape[0]):
    for j in range(mat_5x5.shape[1]):
        if mat_5x5[i][j] % 2 == 0:
            mat_5x5[i][j] = 0
print(f"The even number replaced by 0 matrix is: \n {mat_5x5}")

The diagonal elements are :[1, 7, 13, 19, 25]
The sum of each of the rows of the matrix is: [15, 40, 65, 90, 115]
The elements greater than 12 are :[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
The even number replaced by 0 matrix is: 
 [[ 1.  0.  3.  0.  5.]
 [ 0.  7.  0.  9.  0.]
 [11.  0. 13.  0. 15.]
 [ 0. 17.  0. 19.  0.]
 [21.  0. 23.  0. 25.]]


Task 2.2: Generate 1000 random numbers from a normal distribution with mean=50 and
standard deviation=10. Then calculate and print the actual mean, standard deviation, and the
percentage of values within one standard deviation of the mean.

In [5]:
#Generate 1000 random number
mean = 50
std = 10
nums = np.random.normal(mean,std,1000)

#Mean
mean_val = nums.mean()
print(f"The mean value of the distribution is: {mean_val}")

#Standard Deviation
std_val = nums.std()
print(f"The standard deviation of the distribution is: {std_val}")

#Percetage Values
var_val = nums.var()
print(f"The variance of the distribution is: {var_val}")

The mean value of the distribution is: 49.78430521538091
The standard deviation of the distribution is: 10.346482787867831
The variance of the distribution is: 107.04970607964529


## Data

In [6]:
sample_data = """student_id,name,math_score,english_score,science_score
1,Alice,85,90,88
2,Bob,72,68,75
3,Charlie,90,85,92
4,Diana,65,78,70
5,Eve,88,92,86
6,Frank,75,70,78
7,Grace,95,88,94
8,Henry,68,72,65
"""
with open("students.csv", "w") as f:
 f.write(sample_data)
print("Created students.csv file")

Created students.csv file


# Task 3
Task 3.1: Using the students_df DataFrame:
1. Add a column called "total_score" that sums all three subject scores
2. Add a column called "rank" that ranks students by total_score (1 = highest)
3. Create a new DataFrame containing only students who scored above average in all three
subjects


In [7]:
%pip install pandas 
import pandas as pd

Note: you may need to restart the kernel to use updated packages.


In [14]:
students_df = pd.read_csv("students.csv")
df = students_df.copy()
df.columns = df.columns.str.strip()
print(df)

   student_id     name  math_score  english_score  science_score
0           1    Alice          85             90             88
1           2      Bob          72             68             75
2           3  Charlie          90             85             92
3           4    Diana          65             78             70
4           5      Eve          88             92             86
5           6    Frank          75             70             78
6           7    Grace          95             88             94
7           8    Henry          68             72             65


In [23]:
#Add total_score column
df["total_score"] = (df["math_score"]+df["english_score"]+df["science_score"])

#Rank
df["rank"] = df["total_score"].rank(ascending=False, method="dense").astype(int)
print(f"The dataframe with total scores and rank: \n{df}")

#New datafram of only above average students
avg_score_math = df["math_score"].mean()
avg_score_english = df["english_score"].mean()
avg_score_science = df["science_score"].mean()
df2 = df[
    (df["math_score"] > avg_score_math) &
    (df["english_score"] > avg_score_english) &
    (df["science_score"] > avg_score_science)
]
print(f"\n\nThe dataframe with only above average scoes: \n{df2}")

The dataframe with total scores and rank: 
   student_id     name  math_score  english_score  science_score  total_score  \
0           1    Alice          85             90             88          263   
1           2      Bob          72             68             75          215   
2           3  Charlie          90             85             92          267   
3           4    Diana          65             78             70          213   
4           5      Eve          88             92             86          266   
5           6    Frank          75             70             78          223   
6           7    Grace          95             88             94          277   
7           8    Henry          68             72             65          205   

   rank  
0     4  
1     6  
2     2  
3     7  
4     3  
5     5  
6     1  
7     8  


The dataframe with only above average scoes: 
   student_id     name  math_score  english_score  science_score  total_score  \
0       

Task 3.2: Calculate and display:
1. The correlation between math_score and science_score
2. The student(s) with the highest improvement potential (biggest difference between their
best and worst subject)
3. The average score for each subject

In [ ]:
#Correlation between math_score and science_score
correlation = df["math_score"].corr(df["science_score"])
print(f"Correlation between math_score and science_score: {correlation:.3f}")

#Highest imrpovement potential
df["improvement_potential"] = (
    df[["math_score", "english_score", "science_score"]].max(axis=1) -
    df[["math_score", "english_score", "science_score"]].min(axis=1)
)
max_improvement = df["improvement_potential"].max()
students_with_max_potential = df[
    df["improvement_potential"] == max_improvement
][["student_id", "name", "improvement_potential"]]
print("\nStudent(s) with the highest improvement potential:")
print(students_with_max_potential)

#Average score per subject
average_scores = df[["math_score", "english_score", "science_score"]].mean()
print("\nAverage score for each subject:")
print(average_scores)

Correlation between math_score and science_score: 0.967

Student(s) with the highest improvement potential:
   student_id   name  improvement_potential
3           4  Diana                     13

Average score for each subject:
math_score       79.750
english_score    80.375
science_score    81.000
dtype: float64


: 